### ISSUE TITLE
TransmitFrame hanging sometimes

### ISSUE THREAD

**Issue by johnnyb** [einride/can-go#101]
This is probably a problem with Linux Socketcan (running on a Pi 4), but I thought I would note it in case anyone knew an easy answer.  It's not a huge problem, but one I've found in testing.  Essentially, on occasion, TransmitFrame doesn't return UNTIL I receive a frame on the bus.  It's hard to replicate.  But, in any case, when bus traffic is empty, then the TransmitFrame will, only sometimes, fail to return.  When incoming traffic returns to the bus, TransmitFrame will finally complete.

**Comment by johnnyb** [comment]
Note that writing multiple frames doesn't help.  If I attach a timeout to the write call, I get a continual stream of "transmit frame: write can0: I/o timeout" until a frame is transmitted by another device on the bus, and then everything starts working again.

**Comment by johnnyb** [comment]
This is possibly due to a "bus off" condition.  If the bus is completely disconnected, it will hang, but if I even have a device monitoring the bus, it seems to turn back on.

**Comment by hashemmm96** [comment]
Hi @johnnyb,

One of the prerequisites of the CAN protocol is that there must be at least two devices listening on the bus for correct communication (i.e. two devices must be "bus on"). Trying to transmit on a bus with only one device is not possible.

**Comment by johnnyb** [comment]
I would think there would need to be something that happened besides "hang indefinitely" but since this is known and I have found a workaround for myself I'll close this out.
