### ISSUE TITLE
go.mod content error

### ISSUE THREAD

**Issue by VoSiqiino** [einride/can-go#264]
`module go.einride.tech/can
`

should be

`module github.com/einride/can-go`

**Comment by alethenorio** [comment]
Thank you for the issue. This repository uses what is called a [Vanity URL](https://en.m.wikipedia.org/wiki/Vanity_domain) so `go.einride.tech/can` is indeed the correct module name.

**Comment by Jassob** [comment]
But maybe we should add a MWE in README.md to show that the import path is indeed `go.einride.tech/can`?

**Comment by alethenorio** [comment]
@Jassob good idea
